### ISSUE TITLE
Add `flow` branch

### ISSUE THREAD

**Issue by lorensr** [GraphQLGuide/guide-android#3]
something like this:

```kt  
apolloClient.query( ChaptersQuery()).responseFetcher(ApolloResponseFetchers.CACHE_AND_NETWORK).watcher().toFlow().collect { response ->
    // update UI with new data
}
```

from: https://www.apollographql.com/docs/android/essentials/normalized-cache/#reacting-to-changes-in-the-cache

or maybe better to use `.asLiveData()` instead of `.collect()` https://medium.com/androiddevelopers/lessons-learnt-using-coroutines-flow-4a6b285c0d06

ref `CACHE_AND_NETWORK`: https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/fetcher/ApolloResponseFetchers.java#L46

it will give back data once from the cache, and then again once the network request returns—but probably only the second time if it changes. the data returned by the current queries don't change, so to test, you can change `Sections.graphql` to:

```gql
query Sections($id: Int!) {
  chapter(id: $id) {
    sections {
      number
      title
      content
    }
  }
}
```

(and then rebuild to generate models). the `.content` field will be different after each network request.

**Comment by daniel-stoneuk** [comment]
Since `toFlow()` may return an error, I have added a second LiveData that will store the exception state. I manage exception handling in the map (to get the data out of the Response).

For example:

```kotlin
val chapterList = apolloClient.query(ChaptersQuery())
    .responseFetcher(ApolloResponseFetchers.CACHE_AND_NETWORK).watcher().toFlow().map { response ->
        if (response.hasErrors()) throw Exception("Response has errors")
        val chapters = response.data?.chapters ?: throw Exception("Data is null")
        chapterException.value = null
        return@map chapters
    }.catch { exception ->
        chapterException.postValue(exception)
    }.asLiveData()
```

This means that the exception and result are observed separately in the view. Alternatively, we can use the Response class used in viewmodel branch upstream to handle these exceptions by creating a new Flow that shouldn't ever throw exceptions. To keep things simple and in one place I've left it here. Also see [asLiveData docs](https://developer.android.com/reference/kotlin/androidx/lifecycle/package-summary#aslivedata) for how LiveData manages Flow

I can confirm that the callback for the new list is called twice.

**Comment by lorensr** [comment]
Thanks! 

I see callback is called twice, but it looks like we're also calling `notifyDataSetChanged()` twice—does that unnecessarily re-render the UI? If so, can we check to see if the data changed before calling it?

Looks like `SectionsFragment` no longer has a loading state—can you add that back?

**Comment by daniel-stoneuk** [comment]
You're right, thanks. I'll enable the loading spinner again and implement an item differ for the Adapter.

**Comment by daniel-stoneuk** [comment]
Just double checked and I am seeing the loading spinner on my device, so it should all be working fine now :)

**Comment by lorensr** [comment]
Looks great, thanks.
